P175B602-autonuoma-dotnet-v2/Autonuoma/Controllers/DarbuotojasController.cs
namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers;

using Microsoft.AspNetCore.Mvc;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.Models;

/// <summary>
/// Controller for working with 'Darbuotojas' entity.
/// </summary>
public class DarbuotojasController : ControllerBase
{
    /// <summary>
    /// This is invoked when either 'Index' action is requested or no action is provided.
    /// </summary>
    /// <returns>Entity list view.</returns>
    [HttpGet]
    public ActionResult Index()
    {
        var darbuotojai = DarbuotojasRepo.List();
        return View(darbuotojai); // Ensure this matches the expected model in the Darbuotojas Index view
    }

    /// <summary>
    /// This is invoked when creation form is first opened in browser.
    /// </summary>
    /// <returns>Creation form view.</returns>
    [HttpGet]
    public ActionResult Create()
    {
        var darb = new Darbuotojas();
        return View(darb);
    }

    /// <summary>
    /// This is invoked when buttons are pressed in the creation form.
    /// </summary>
    /// <param name="darb">Entity model filled with latest data.</param>
    /// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
    [HttpPost]
    public ActionResult Create(Darbuotojas darb)
    {
        //do not allow creation of entity with 'asmensKodas' field matching existing one
        var match = DarbuotojasRepo.Find(darb.AsmensKodas);

        if (match != null)
            ModelState.AddModelError("asmensKodas", "Field value already exists in database.");

        //form field validation passed?
        if (ModelState.IsValid)
        {
            //NOTE: insert will fail if someone managed to add different 'darbuotojas' with same 'asmensKodas' after the check
            DarbuotojasRepo.Insert(darb);

            //save success, go back to the entity list
            return RedirectToAction("Index");
        }

        //form field validation failed, go back to the form
        return View(darb);
    }

    /// <summary>
    /// This is invoked when editing form is first opened in browser.
    /// </summary>
    /// <param name="id">ID of the entity to edit.</param>
    /// <returns>Editing form view.</returns>
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View(DarbuotojasRepo.Find(id));
    }

    /// <summary>
    /// This is invoked when buttons are pressed in the editing form.
    /// </summary>
    /// <param name="id">ID of the entity being edited</param>		
    /// <param name="darb">Entity model filled with latest data.</param>
    /// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
    [HttpPost]
    public ActionResult Edit(int id, Darbuotojas darb)
    {
        //form field validation passed?
        if (ModelState.IsValid)
        {
            DarbuotojasRepo.Update(darb);

            //save success, go back to the entity list
            return RedirectToAction("Index");
        }

        //form field validation failed, go back to the form
        return View(darb);
    }

    /// <summary>
    /// This is invoked when deletion form is first opened in browser.
    /// </summary>
    /// <param name="id">ID of the entity to delete.</param>
    /// <returns>Deletion form view.</returns>
    [HttpGet]
    public ActionResult Delete(int id)
    {
        var darb = DarbuotojasRepo.Find(id);
        return View(darb);
    }

    /// <summary>
    /// This is invoked when deletion is confirmed in deletion form
    /// </summary>
    /// <param name="id">ID of the entity to delete.</param>
    /// <returns>Deletion form view on error, redirects to Index on success.</returns>
    [HttpPost]
    public ActionResult DeleteConfirm(int id)
    {
        //try deleting, this will fail if foreign key constraint fails
        try
        {
            DarbuotojasRepo.Delete(id);

            //deletion success, redired to list form
            return RedirectToAction("Index");
        }
        //entity in use, deletion not permitted
        catch (MySql.Data.MySqlClient.MySqlException)
        {
            //enable explanatory message and show delete form
            ViewData["deletionNotPermitted"] = true;

            var darb = DarbuotojasRepo.Find(id);
            return View("Delete", darb);
        }
    }
}

P175B602-autonuoma-dotnet-v2/Autonuoma/Controllers/KlientasController.cs
namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers;

using Microsoft.AspNetCore.Mvc;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.Models;

/// <summary>
/// Controller for working with 'Klientas' entity.
/// </summary>
public class KlientasController : ControllerBase
{
    /// <summary>
    /// This is invoked when either 'Index' action is requested or no action is provided.
    /// </summary>
    /// <returns>Entity list view.</returns>
    [HttpGet]
    public ActionResult Index()
    {
        return View(KlientasRepo.List());
    }

    /// <summary>
    /// This is invoked when creation form is first opened in browser.
    /// </summary>
    /// <returns>Creation form view.</returns>
    [HttpGet]
    public ActionResult Create()
    {
        var klientas = new Klientas();
        return View(klientas);
    }

    /// <summary>
    /// This is invoked when buttons are pressed in the creation form.
    /// </summary>
    /// <param name="klientas">Entity model filled with latest data.</param>
    /// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
    [HttpPost]
    public ActionResult Create(Klientas klientas)
    {
        //do not allow creation of entity with 'asmensKodas' field matching existing one
        var match = KlientasRepo.Find(klientas.AsmensKodas);

        if (match != null)
            ModelState.AddModelError("asmensKodas", "Field value already exists in database.");

        //form field validation passed?
        if (ModelState.IsValid)
        {
            KlientasRepo.Insert(klientas);

            //save success, go back to the entity list
            return RedirectToAction("Index");
        }

        //form field validation failed, go back to the form
        return View(klientas);
    }

    /// <summary>
    /// This is invoked when editing form is first opened in browser.
    /// </summary>
    /// <param name="id">ID of the entity to edit.</param>
    /// <returns>Editing form view.</returns>
    [HttpGet]
    public ActionResult Edit(int id)
    {
        return View(KlientasRepo.Find(id));
    }

    /// <summary>
    /// This is invoked when buttons are pressed in the editing form.
    /// </summary>
    /// <param name="id">ID of the entity being edited</param>		
    /// <param name="klientas">Entity model filled with latest data.</param>
    /// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
    [HttpPost]
    public ActionResult Edit(int id, Klientas klientas)
    {
        //form field validation passed?
        if (ModelState.IsValid)
        {
            KlientasRepo.Update(klientas);

            //save success, go back to the entity list
            return RedirectToAction("Index");
        }

        //form field validation failed, go back to the form
        return View(klientas);
    }

    /// <summary>
    /// This is invoked when deletion form is first opened in browser.
    /// </summary>
    /// <param name="id">ID of the entity to delete.</param>
    /// <returns>Deletion form view.</returns>
    [HttpGet]
    public ActionResult Delete(int id)
    {
        var klientas = KlientasRepo.Find(id);
        return View(klientas);
    }

    /// <summary>
    /// This is invoked when deletion is confirmed in deletion form
    /// </summary>
    /// <param name="id">ID of the entity to delete.</param>
    /// <returns>Deletion form view on error, redirects to Index on success.</returns>
    [HttpPost]
    public ActionResult DeleteConfirm(int id)
    {
        //try deleting, this will fail if foreign key constraint fails
        try
        {
            KlientasRepo.Delete(id);

            //deletion success, redired to list form
            return RedirectToAction("Index");
        }
        //entity in use, deletion not permitted
        catch (MySql.Data.MySqlClient.MySqlException)
        {
            //enable explanatory message and show delete form
            ViewData["deletionNotPermitted"] = true;

            var klientas = KlientasRepo.Find(id);
            return View("Delete", klientas);
        }
    }
}

P175B602-autonuoma-dotnet-v2/Autonuoma/Views/_DoNothing.cshtml
@* this will also be used as page title in main layout *@
@{ ViewData["title"] = "Page to use instead of redirect view if you want to see queries."; }

@* content header *@
<div class="main-content-header">
	<span class="title">@ViewData["title"]</span>
    <span class="actions">
		<a 
			href="@Url.Action("Index")" 
			class="btn btn-outline-primary btn-sm"
		>
			<i class="fa-solid fa-angles-left"></i> Atgal į sarašą
		</a>
	</span>
</div>

@* content itself *@
<div class="p-3">
    <p>This view exists, so that you can see queries executed in actions that use <i>return RedirectToAction("Index");</i>.</p>
    <p>Use <i>return View("_DoNothing");</i> instead, to render this view instead of redirection.</p>
</div>

@* content footer *@
<div class="main-content-footer">
	<span class="title"></span>
	<span class="actions">
		<a 
			href="@Url.Action("Index")" 
			class="btn btn-outline-primary btn-sm"
		>
			<i class="fa-solid fa-angles-left"></i> Atgal į sarašą
		</a>
	</span>
</div>

P175B602-autonuoma-dotnet-v2/Autonuoma/Views/_Exception.cshtml
@* this will also be used as page title in main layout *@
@{ ViewData["title"] = "Unhandled exception was caught in controller action."; }

@* content header *@
<div class="main-content-header">
	<span class="title">@ViewData["title"]</span>
</div>

@* content itself *@
<div class="p-3">
    <p>This page exists, so that you can still see queries executed before the exception, in the browser console.</p>
    <p>Use a debugger to inspect the exception, your IDE should have paused on it.</p>
    <p>If exception was thrown due to query, you can inspect the query SQL in result of <i>var sql = RecordCommandSql(dbCmd);</i> inside the corresponding query method of <i>Sql</i> class.</p>
</div>

P175B602-autonuoma-dotnet-v2/Autonuoma/Views/_Layout.cshtml
@{
	/// <summary>
	/// Helper for marking active links in main menu.
	/// </summary>
	/// <param name="ctrl">Controller to look for.</param>
	/// <param name="act">Action to look for. Pass null if action does not matter.</param>
	/// <returns>If controller and (optionally) action match given ones returns "active". Returns empty string otherwise.</returns>
	string MarkActive(string ctrl, string act = null)
	{
		//get current controller and action
		var curCtrl = (string)ViewContext.RouteData.Values["Controller"];
		var curAct = (string)ViewContext.RouteData.Values["Action"];

		//compare to given ones
		if( curCtrl == ctrl && (act == null || curAct == act) )
			return "active";
		return "";
	}
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	@* ViewData["title"] gets set in view templates *@
	<title>Autonuoma - @ViewData["title"]</title>

	<script>
	//<![CDATA[
		//this will contain BASE64 encoded SQL queries used to render the page, set by ControllerBase.OnActionExecuted()
		var base64JsonSqlQueries = "@Html.Raw(ViewData["sql-queries"])";
	//]]>
	</script>

	<!-- this contains core scripts and styles and is built by webpack -->
	<script src="@Url.Content("~/deps/dist/main.js")"></script>

	<!-- you can use these to add your own scripts and styles quickly -->
	<script src="@Url.Content("~/deps-manual/index.js")"></script>
	<link href="@Url.Content("~/deps-manual/style.css")" rel="stylesheet"/>
	
	<script>
	//<![CDATA[
		//pull in top most jQuery function exposed from module built by webpack; for use in jQuery plug-in initialization code
		var $ = window.__jQuery;
	//]]>
	</script>
</head>
<body>
	<div class="page-container">
		@* page header, also main menu *@
		<nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
			<div class="container-fluid">
				@* home button *@
				<a class="navbar-brand" href="@Url.Action("Index", "Home")" class="navbar-brand"><i class="fa-solid fa-car"></i></a>

				@* this buttons shows drop down menu on narrow screens; it is invisible normally *@
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarContent"
				>
					<span class="navbar-toggler-icon"></span>
				</button>

				@* menu links for forms and reports *@
				<div class="container-fluid d-flex justify-content-center">
					<div class="collapse navbar-collapse" id="navbarContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							@* main menu links go here *@
							<li class="nav-item">
								<a href="@Url.Action("Index", "SutartisF2")" class="@MarkActive("SutartisF2") nav-link">Sutartys (F2)</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Paslauga")" class="@MarkActive("Paslauga") nav-link">Paslaugos</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Klientas")" class="@MarkActive("Klientas") nav-link">Klientai</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Darbuotojas")" class="@MarkActive("Darbuotojas") nav-link">Darbuotojai</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Automobilis")" class="@MarkActive("Automobilis") nav-link">Automobiliai</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Marke")" class="@MarkActive("Marke") nav-link">Markės</a>
							</li>
							<li class="nav-item">
								<a href="@Url.Action("Index", "Modelis")" class="@MarkActive("Modelis") nav-link">Modeliai</a>
							</li>
						</ul>

						@* drop-down menu for report links *@
						<ul class="navbar-nav justify-content-right mb-2 mb-lg-0">
							<li class="nav-item dropdown">
								<a
									class="@MarkActive("Report") nav-link dropdown-toggle"
									href="#"
									id="navbarReports"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
									Ataskaitos
								</a>
								<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarReports">
									@* report links go here *@									
									<li>
										<a
											href="@Url.Action("Contracts", "Reports")"
											class="@MarkActive("Reports", "Contracts") dropdown-item"
										>Sutarčių ataskaita</a>
									</li>
									<li>
										<a
											href="@Url.Action("LateContracts", "Reports")"
											class="@MarkActive("Reports", "LateContracts") dropdown-item"
										>Vėluojančių sutarčių ataskaita (neįskaitinė)</a>
									</li>
									<li>
										<a
											href="@Url.Action("Services", "Reports")"
											class="@MarkActive("Reports", "Services") dropdown-item"
										>Paslaugų ataskaita (neįskaitinė)</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>

		@* main content gets rendered here *@
		<div class="main-content">
			@RenderBody()
		</div>

		@* page footer *@
		<div class="page-footer">
			<footer>
				<p>&copy; KTU Informacijos Sistemų Katedra</p>
			</footer>
		</div>
	</div>
	
	@* any JavaScript code comming from script sections in views gets rendered here *@
	@RenderSection("scripts", required: false)

	@* JavaScript code initialization routines go here *@
	<script>
	//<![CDATA[
		//this function gets invoked by the browser when HTML page is fully loaded
		$(document).ready(function () {
			//apply jQuery datatables plugin on tables having CSS class 'entity-list'
			$(".entity-list").DataTable({
				"autoWidth": true,
				language : {
					"decimal":        "",
					"emptyTable":     "Įrašų nėra",
					"info":           "Įrašai nuo _START_ iki _END_ iš _TOTAL_",
					"infoEmpty":      "0",
					"infoFiltered":   "(iš _MAX_ įrašų)",
					"infoPostFix":    "",
					"thousands":      ",",
					"lengthMenu":     "Puslapyje: _MENU_",
					"loadingRecords": "Vyksta duomenų įkėlimas...",
					"processing":     "Vyksta apdorojimas...",
					"search":         "Paieška:",
					"zeroRecords":    "Įrašų nerasta",
					"paginate": {
						"first":      "Pirmas",
						"last":       "Paskutinis",
						"next":       "Sekantis",
						"previous":   "Buvęs"
					},
					"aria": {
						"sortAscending":  ": rikiuoti didėjimo tvarka",
						"sortDescending": ": rikiuoti mažėjimo tvarka"
					}
				}
			});

			//apply jQuery datetimepicker plugin on fields having CSS classes 'date-picker' and 'datetime-picker'
			$(".date-picker").datetimepicker({ timepicker:false, format: 'Y-m-d' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' });
		});
	//]]>
	</script>
</body>
</html>